### ISSUE TITLE
Assignment 01 -- 23-aug-2023

### ISSUE THREAD

**Issue by dudung** [dudung/fi4002-01-2023-1#1]
+ Create Medium account for this course &rightarrow; [link](https://medium.com/m/signin)
+ Create GitHub account for this course &rightarrow; [link](https://github.com/signup?source=login)
+ Fork this repository for update of this course &rightarrow; [this](https://github.com/dudung/fi4002-01-2023-1/fork).
+ Report your NIM, username for Medium and GitHub, and link to forked repository here and also in [Edunex](https://edunex.itb.ac.id/courses/52864/edit/184898/81565).
+ Deadline for this assignment is **24 Aug 2023**.

```
+ 19927099
+ https://medium.com/@rrkurnova
+ https://github.com/rrkurnova
+ https://github.com/rrkurnova/fi4002-01-2023-1
```

**Comment by rrkurnova** [comment]
+ 19927099
+ https://medium.com/@rrkurnova
+ https://github.com/rrkurnova
+ https://github.com/rrkurnova/fi4002-01-2023-1

**Comment by BergasBintang** [comment]
- 10219007
- https://medium.com/@bergasbintang16
- https://github.com/BergasBintang
- https://github.com/BergasBintang/SPSF

**Comment by MaynardoPS** [comment]
+ 10220063
+ https://medium.com/@maynardosoegianto
+ https://github.com/MaynardoPS
+ https://github.com/MaynardoPS/fi4002-01-2023-1

**Comment by Sarahaul** [comment]
• 10220080
• https://medium.com/@sarahauliyaurrohman52
• https://github.com/Sarahaul
• https://github.com/Sarahaul/fi4002-01-2023-1

**Comment by BernardSujono** [comment]
• 10220011
• https://medium.com/@bernardsujono10
• https://github.com/BernardSujono
• https://github.com/BernardSujono/fi4002-01-2023-1

**Comment by azkabudiman21** [comment]
- 10219056
- https://medium.com/@azkabudiman
- https://github.com/azkabudiman21
- https://github.com/azkabudiman21/fi4002-01-2023-1

**Comment by MalikAnshari-048** [comment]
- 10220048
- https://medium.com/@malik.el.anshary
- https://github.com/MalikAnshari-048
- https://github.com/MalikAnshari-048/fi4002-01-2023-1

**Comment by desulight99** [comment]
- 10220082
- https://medium.com/@desulight99
- https://github.com/desulight99
- https://github.com/desulight99/fi4002-01-2023-1

**Comment by saaniyara** [comment]
- 10220076
- https://medium.com/@tsaniyahhz
- https://github.com/tsaniyahhz
- https://github.com/tsaniyahhz/fi4002-01-2023-1

**Comment by andrewanggoh** [comment]
+ 10220012
+ https://medium.com/@andrew.anggoh
+ https://github.com/andrewanggoh
+ https://github.com/andrewanggoh/fi4002-01-2023-1

**Comment by AngeliFransiskaNjo** [comment]
- 10220022
- https://medium.com/@angelifransiskanjoo
- https://github.com/AngeliFransiskaNjo
- https://github.com/AngeliFransiskaNjo/fi4002-01-2023-1

**Comment by clarissastvn** [comment]
+ 10220042
+ https://medium.com/@clarissastvn
+ https://github.com/clarissastvn
+ https://github.com/clarissastvn/fi4002-01-2023-1

**Comment by cyukis** [comment]
10220056
https://medium.com/@cyukis
https://github.com/cyukis
https://github.com/cyukis/fi4002-01-2023-1

**Comment by cyukis** [comment]
+ 10220056
+ https://medium.com/@cyukis
+ https://github.com/cyukis
+ https://github.com/cyukis/fi4002-01-2023-1

**Comment by arionlubis** [comment]
+ 10220047
+ https://medium.com/@arionlubis
+ https://github.com/arionlubis
+ https://github.com/arionlubis/fi4002-01-2023-1

**Comment by yuliajanah** [comment]
+ 10219075
+ https://medium.com/@yuliajanah041
+ https://github.com/yuliajanah
+ https://github.com/yuliajanah/fi4002-01-2023-1

**Comment by rafifprastya** [comment]
+ 10220033
+ https://medium.com/@rafifprastya
+ https://github.com/rafifprastya
+ https://github.com/rafifprastya/fi4002-01-2023-1

**Comment by NurlailaTan** [comment]
10219076
https://medium.com/@nurlailahtan
https://github.com/NurlailaTan
https://github.com/NurlailaTan/fi4002-01-2023-1

**Comment by yusuff10** [comment]
> 

- 10220021
- https://medium.com/@yusuf_f10
- https://github.com/yusuff10
- https://github.com/yusuff10/fi4002-01-2023-1

**Comment by dianatan** [comment]
- 10220038
- https://medium.com/@dtanoto88
- https://github.com/dianatan
- https://github.com/dianatan/fi4002-01-2023-1

**Comment by deyselezra** [comment]
- 10220071

- https://medium.com/@deysel040402

- https://github.com/deyselezra

- https://github.com/deyselezra/fi4002-01-2023-1

**Comment by winieamellia** [comment]
+ 10220055
+ https://medium.com/@winamellia88
+ https://github.com/winieamellia
+ https://github.com/winieamellia/fi4002-01-2023-1

**Comment by keziaalodiac** [comment]
- 10220009
- https://medium.com/@keziaalodiac
- https://github.com/keziaalodiac
- https://github.com/keziaalodiac/fi4002-01-2023-1

**Comment by ElizabethMichele** [comment]
**_10220004_**
- https://medium.com/@elizabeth.michelee
- https://github.com/ElizabethMichele
- https://github.com/ElizabethMichele/fi4002-01-2023-1

**Comment by ArkanantaR** [comment]
10220014

- https://medium.com/@arkanantaltmpt
- https://github.com/ArkanantaR
- https://github.com/ArkanantaR/fi4002-01-2023-1

**Comment by BerlianOkaI** [comment]
- 10220037
- https://medium.com/@varhitera21
- https://github.com/BerlianOkaI
- https://github.com/BerlianOkaI/fi4002-01-2023-1_ForkedEC

**Comment by fatihahjazaaufa** [comment]
- 10220013
- https://medium.com/@fatihahjaza
- https://github.com/fatihahjazaaufa
- https://github.com/fatihahjazaaufa/fi4002-01-2023-1

**Comment by RizkiArdikaF** [comment]
- 10219023
- https://medium.com/@rizki.ardika.f
- https://github.com/RizkiArdikaF
- https://github.com/RizkiArdikaF/fi4002-01-2023-1

**Comment by zadzanl** [comment]
+ 10220060
+ https://medium.com/@z.adzani
+ https://github.com/zadzanl
+ https://github.com/zadzanl/SPSF-FI4002-20231

**Comment by gitaameliiaa** [comment]
- 10220018
- [medium.com/@gitaameliamarianto26]
- https://github.com/gitaameliiaa
- https://github.com/gitaameliiaa/fi4002-01-2023-1

**Comment by purwariadi** [comment]
+ 10219109
+ https://medium.com/@purwasatria
+ https://github.com/purwariadi
+ https://github.com/purwariadi/fi4002-01-2023-1

**Comment by elsbthbunga** [comment]
10220068
https://medium.com/@elsbthbunga
https://github.com/elsbthbunga
https://github.com/elsbthbunga/fi4002-01-2023-1

**Comment by elsbthbunga** [comment]
- 10220068
- https://medium.com/@elsbthbunga
- https://github.com/elsbthbunga
- https://github.com/elsbthbunga/fi4002-01-2023-1

**Comment by kaniedo25** [comment]
- 10219009
- https://medium.com/@kaniedo
- https://github.com/kaniedo25
- https://github.com/kaniedo25/fi4002-01-2023-1

**Comment by Voxxis11** [comment]
10220035
https://medium.com/@aldiarbie
https://github.com/Voxxis11
https://github.com/Voxxis11/fi4002-01-2023-1

**Comment by DedeAditiaa** [comment]
10220007
https://medium.com/@dedeaditiaa
https://github.com/DedeAditiaa
https://github.com/DedeAditiaa/fi4002-01-2023-1

**Comment by syakuradhya** [comment]
10220073
https://medium.com/@syakuradhya
https://github.com/syakuradhya
https://github.com/syakuradhya/fi4002-01-2023-1

**Comment by BracchialisG** [comment]
10220067
https://medium.com/@rekryanta
https://github.com/BracchialisG
https://github.com/BracchialisG/FI4002-1-2023-1

**Comment by BayuHDN26** [comment]
- 10023119
- https://medium.com/@bayuharnadi262
- https://github.com/BayuHDN26
- https://github.com/BayuHDN26/fi4002-01-2023-1

**Comment by emahdyt** [comment]
- 10220051
- https://medium.com/@emahdyt
- https://github.com/emahdyt
- https://github.com/emahdyt/fi4002-01-2023-1

**Comment by SurbaktiAlloy** [comment]
+ 10220031
+ https://medium.com/@alloychristian07
+ https://github.com/SurbaktiAlloy
+ https://github.com/SurbaktiAlloy/fi4002-01-2023-1
