### ISSUE TITLE
Assignment 02 -- 25-aug-2023

### ISSUE THREAD

**Issue by dudung** [dudung/fi4002-01-2023-1#2]
+ Write an article in Medium with at least **five minutes** reading time.
+ Describe you impression in the first week lecture.
+ Share what you expect to learn in the course.
+ State you commitment, e.g. time you want to invest, discussion group you form, video you plan to watch, etc.
+ Explain your plan and strategy to accomplish the course with highest grade.
+ Say explicitly the grade you want to obtain, e.g. A or AB or others.
+ Other things you believe worth to share with other course participants.
+ Report your NIM and link to the article, also the title or the article, here and also in [Edunex](https://edunex.itb.ac.id/courses/52864/preview/184898/82433) as follow.

```
+ 19927099
+ https://medium.com/@rrkurnova/767cb5ca0c54
+ Pindah kelas atau tidak? Atau tunggu semester depan?
```

**Comment by rrkurnova** [comment]
+ 19927099
+ https://medium.com/@rrkurnova/767cb5ca0c54
+ Pindah kelas atau tidak? Atau tunggu semester depan?

**Comment by keziaalodiac** [comment]
- 10220009
- https://medium.com/@keziaalodiac/3-alasan-jangan-mengambil-mata-kuliah-simulasi-dan-pemodelan-sistem-fisis-bersama-pak-dudung-f44200c9a185
- 3 Alasan Jangan Mengambil SPSF Bersama Pak Dudung

**Comment by NurlailaTan** [comment]
•	10219076
•	https://medium.com/@nurlailahtan/jangan-ambil-spsf-kelas-ini-kalau-belum-6e696ec4aaf6
•	Jangan ambil SPSF kelas ini kalau belum…

**Comment by BayuHDN26** [comment]
- 10023119
- https://medium.com/@bayuharnadi262/from-ayam-jantan-to-ganesha-300283bf62e3
- From Ayam Jantan to Ganesha

**Comment by BracchialisG** [comment]
- 10220067
- https://medium.com/@rekryanta/kalau-bisa-sulit-mengapa-harus-mudah-dcdda1033c18
- Kalau Bisa Sulit Mengapa Harus Mudah?

**Comment by Sarahaul** [comment]
• 10220080
• https://medium.com/@sarahauliyaurrohman52/simulasi-fisika-sebagai-kemajuan-397b3bfdc8f2
• Simulasi Fisika sebagai Kemajuan

**Comment by MalikAnshari-048** [comment]
- 10220048
- https://medium.com/@malik.el.anshary/prolog-fi4002-k01-795c77e83427
- Prolog FI4002 K01

**Comment by emahdyt** [comment]
- 10220051
- https://medium.com/@ermas.hidayati/ambil-saat-semester-7-atau-8-a9d597738852
- Ambil di semester 7 atau 8?

**Comment by kaniedo25** [comment]
- 10219009
- https://medium.com/@kaniedo/alkisah-yang-agak-resah-dikit-saat-kelas-spsf-with-pak-9npnp-613f368c45e6
- Alkisah yang Agak Resah Dikit saat Kelas SPSF with Pak 9npnp

**Comment by syakuradhya** [comment]
- 10220073
- https://syakuradhya.medium.com/3bbf7ae1b57b
- Simulasi dan Pemodelan Sistem Fisis Belajar Apa, sih?

**Comment by BernardSujono** [comment]
10220011
https://medium.com/@bernardsujono10/how-to-drop-this-spsf-class-afc858637b96
How to Drop SMPS Class?

**Comment by BernardSujono** [comment]
• 10220011
• https://medium.com/@bernardsujono10/how-to-drop-this-spsf-class-afc858637b96
• How to Drop SMPS Class?

**Comment by yuliajanah** [comment]
10219075
https://medium.com/@yuliajanah041/berawal-dari-mengobrol-dengan-kakak-tingkat-berbagai-angkatan-dan-teman-seangkatan-fisika-2019-b5cd33e88838
berawal-dari-mengobrol-dengan-kakak-tingkat-berbagai-angkatan-dan-teman-seangkatan-fisika-2019

**Comment by yusuff10** [comment]
- 10220021
- https://medium.com/@yusuf_f10/spsf-memudahkan-atau-menyulitkan-mahasiswa-fisika-a807bf0cb07d
- SPSF Memudahkan atau Menyulitkan Mahasiswa Fisika?

**Comment by Voxxis11** [comment]
- 10220035
- https://medium.com/@aldiarbie/spsf-adalah-modal-19eba25a1a4b
- SPSF Adalah Modal…

**Comment by azkabudiman21** [comment]
- 10219056
- https://medium.com/@azkabudiman/chances-ad44f44b9722
- Chances

**Comment by BerlianOkaI** [comment]
- 10220037
- https://medium.com/@varhitera21/kuliah-pertama-di-simulasi-dan-pemodelan-sistem-fisis-c98aa7a2e84e
- Kuliah Pertama di Simulasi dan Pemodelan Sistem Fisis

**Comment by cyukis** [comment]
+ 10220056
+ https://medium.com/@cyukis/dapat-jurusan-yang-paling-dihindari-gak-geter-sorry-ebe57a87b759
+ Dapat Jurusan yang Paling Dihindari? Gak Geter Sorry

**Comment by elsbthbunga** [comment]
- 10220068
- https://medium.com/@elsbthbunga/e8e9292e52b6
- FI4002 is it worth it ?

**Comment by gitaameliiaa** [comment]
- 10220018
- https://medium.com/@gitaameliamarianto26/spsf-is-it-important-ff875638862d
- Simulation and Modelling of Physical Systems? Is It Important?

**Comment by ArkanantaR** [comment]
- 10220014
- https://arkanantaltmpt.medium.com/just-started-by-a-dead-calculator-194645f211c9
- Just Started by A Dead Calculator

**Comment by clarissastvn** [comment]
+ 10220042
+ https://medium.com/@clarissastvn/memang-boleh-se-simulasi-itu-16c097e17500
+ Memang Boleh se-Simulasi Itu?

**Comment by dianatan** [comment]
- 10220038
- https://medium.com/@dtanoto88/e8cac8d6422f
- SPSF, Yay or Nay?

**Comment by desulight99** [comment]
- 10220082
- https://medium.com/@desulight99/prolog-34a1d909967b
- Simulasi yang tidak lepas dari fisika

**Comment by fatihahjazaaufa** [comment]
- 10220013
- https://medium.com/@fatihahjaza/baca-ini-agar-lebih-yakin-belajar-spsf-bersama-pak-dudung-3646e9ce9db9
- Baca Ini agar Lebih Yakin Belajar SPSF Bersama Pak Dudung

**Comment by AngeliFransiskaNjo** [comment]
- 10220022
- https://medium.com/@angelifransiskanjoo/ikut-kelas-spsfnya-pak-dudung-mau-cari-apasih-7b36840c42b0
- Rela Sit In Demi Ikut Kelas SPSF Pak Dudung?! Berikut 5 Alasannya, nomor 3 bikin geleng-geleng

**Comment by BergasBintang** [comment]
- 10219007
- https://medium.com/@bergasbintang16/percobaan-kedua-apakah-berhasil-43c55cce5b07
- Percobaan Kedua, Apakah Berhasil?

**Comment by arionlubis** [comment]
- 10220047
- https://arionlubis.medium.com/teka-teki-itu-bernama-spsf-8273720f444d
- Teka-Teki itu bernama "SPSF"

**Comment by saaniyara** [comment]
- 10220076
- https://medium.com/@tsaniyahhz/menentukan-pilihan-untuk-mendapatkan-kehidupan-yang-lebih-baik-27a980c675d5
- Menentukan Pilihan untuk Mendapatkan Kehidupan yang Lebih Baik

**Comment by ElizabethMichele** [comment]
- **_10220004_**
- https://medium.com/@elizabeth.michelee/pak-dudung-dan-kelas-simulasi-pemodelan-sistem-fisis-dan-pak-dudung-f50e2fb5d9c1
- Pak Dudung x SPSF (Kelas Full di PRS?)

**Comment by RizkiArdikaF** [comment]
- 10219023
- https://medium.com/@rizki.ardika.f/future-full-of-agony-my-first-impression-of-dr-viridi-spsf-class-c8a9ec75a004
- Future Full of Agony: My First Impression of Dr. Viridi SPSF Class

**Comment by winieamellia** [comment]
- 10220055
- https://medium.com/@winamellia88/2023-era-di-mana-kemajuan-teknologi-digital-berkembang-dengan-sangat-pesat-d952d8ec4e8f
- SPSF dan Revolusi Teknologi

**Comment by DedeAditiaa** [comment]
- 10220007
- https://medium.com/@dedeaditiaa/awal-adalah-bagian-terpenting-dalam-hidup-931438a0c876
- Kamyu nanyea ? Kamyu bertanyea tanyea kenapa saya ngambil SPSF ?

**Comment by purwariadi** [comment]
- 10219109
- https://medium.com/@purwasatria/nanti-kita-cerita-tentang-spsf-ini-d9579c6b33fb
- Nanti Kita Cerita Tentang SPSF Ini

**Comment by rafifprastya** [comment]
+ 10220033
+ https://medium.com/@rafifprastya/mengenal-spsf-1d11ea76dc0
+ Mengenal SPSF

**Comment by MaynardoPS** [comment]
+ 10220063
+ https://medium.com/@maynardosoegianto/how-to-not-survive-in-smps-48a5a35a448d
+ How to (not) survive in SMPS?

**Comment by deyselezra** [comment]
- 10220071
- https://medium.com/@deysel040402/apa-boleh-buat-28ace2e77652
- Apa Boleh Buat?

**Comment by SurbaktiAlloy** [comment]
+ 10220031
+ https://medium.com/@alloychristian07/kenapa-harus-belajar-spsf-4182138b0b27
+ Kenapa Harus Belajar SPSF?

**Comment by andrewanggoh** [comment]
+ 10220012
+ https://medium.com/@andrew.anggoh/spsf-bersama-pak-dudung-9073bf2d6050
+ SPSF Bersama Pak Dudung
