### ISSUE TITLE
Assignment 05- 12-sep-2023

### ISSUE THREAD

**Issue by dudung** [dudung/fi4002-01-2023-1#5]
+ Read the book **Essential Python for the Physicist** by Giovanni Moruzzi ([link](https://link.springer.com/book/10.1007/978-3-030-45027-4))
+ Make an article in Medium as summary for Chapter 3 Plotting with Matplotlib.
+ Report you NIM, title of your article, and link to the article here and also on [Edunex](https://edunex.itb.ac.id/courses/52864/preview/195472/84694).

**Comment by MalikAnshari-048** [comment]
- 10220048
- Properti Dasar Matplotlib
- https://medium.com/@malik.el.anshary/properti-dasar-matplotlib-b01afc166224

**Comment by BerlianOkaI** [comment]
- 10220037
- Membuat Grafik dengan Matplotlib
- https://medium.com/@varhitera21/membuat-grafik-dengan-matplotlib-c622fa53817d

**Comment by Voxxis11** [comment]
- 10220035
- Mengenal Dasar Plotting Menggunakan Python
- https://medium.com/@aldiarbie/mengenal-dasar-plotting-menggunakan-python-f01e26878159

**Comment by Sarahaul** [comment]
- 10220080
- Summary "Plotting with Matplotlib"
- https://medium.com/@sarahauliyaurrohman52/summary-plotting-with-matplotlib-9e5ba16b38c4

**Comment by NurlailaTan** [comment]
- 10219076
- Mari Berkenalan dengan : Plotting with Matplotlib
- https://medium.com/@nurlailahtan/mari-berkenalan-dengan-plotting-with-matplotlib-c92718998823

**Comment by ElizabethMichele** [comment]
- **_10220004_**
- Membuat Grafik dengan Matplotlib dalam Python
- https://medium.com/@elizabeth.michelee/cara-membuat-grafik-dengan-matplotlib-dalam-python-ef41bdf2695d

**Comment by fatihahjazaaufa** [comment]
10220013
Plotting Menggunakan Matplotlib
https://medium.com/@fatihahjaza/plotting-menggunakan-matplotlib-13b5f985a1bb

**Comment by yuliajanah** [comment]
- 10219075
- Essential Python for the Physicist by Giovanni Moruzzi : Summary Chapter 3
- https://medium.com/@yuliajanah041/essential-python-for-the-physicist-by-giovanni-moruzzi-summary-chapter-3-941674aeb87d

**Comment by RizkiArdikaF** [comment]
- 10219023
- Making Plot in Python
- https://medium.com/@rizki.ardika.f/making-plot-in-python-a01f983e46fe

**Comment by kaniedo25** [comment]
- 10219009
- Mari Ber-Plotting Bersama Matplotlib-nya si Python
- https://medium.com/@kaniedo/mari-ber-plotting-bersama-matplotlib-nya-si-python-39d999193532

**Comment by syakuradhya** [comment]
- 10220073
- Matplotlib: Visualisasi dengan Python
- https://syakuradhya.medium.com/matplotlib-visualisasi-dengan-python-bdf4aff12247

**Comment by winieamellia** [comment]
- 10220055
- Python: Plotting with Matplotlib
- https://medium.com/@winamellia88/python-plotting-with-matplotlib-ea1920a1ef13

**Comment by yusuff10** [comment]
- 10220021
- Berkenalan Dengan Matplotlib
- https://medium.com/@yusuf_f10/berkenalan-dengan-matplotlib-cd36f271c1cc

**Comment by emahdyt** [comment]
- 10220051
- Plotting Grafik dengan Matplotlib
- https://medium.com/@ermas.hidayati/plotting-grafik-dengan-matplotlib-b89de55034f9

**Comment by clarissastvn** [comment]
+ 10220042
+ Belajar Plotting dengan Matplotlib
+ https://medium.com/@clarissastvn/belajar-plotting-dengan-matplotlib-ff28f94ca2e9

**Comment by MaynardoPS** [comment]
+ 10220063
+ Plotting Kok Pake Matplotlib-nya Python?
+ https://medium.com/@maynardosoegianto/plotting-kok-pake-matplotlib-nya-python-496f108fdde2

**Comment by gitaameliiaa** [comment]
- 10220018
- Matplotlib: For a Better Visualization
- https://medium.com/@gitaameliamarianto26/matplotlib-for-a-better-visualization-50899b7da45a

**Comment by elsbthbunga** [comment]
- 10220068
- Plotting dalam Python dengan Matplotlib
- https://medium.com/@elsbthbunga/plotting-dalam-python-dengan-matplotlib-2b29300a10ac

**Comment by saaniyara** [comment]
- 10220076
- Menjalankan Peran sebagai Mahasiswa Fisika — 02 Mengenal Matplotlib; Pyplot
- https://medium.com/@tsaniyahhz/menjalankan-peran-sebagai-mahasiswa-fisika-02-mengenal-matplotlib-pyplot-745bd93a7932

**Comment by BernardSujono** [comment]
- 10220011
- MATLAB is more fun than Python
- https://medium.com/@bernardsujono10/mathlab-is-more-fun-than-python-fd146dd89baf

**Comment by desulight99** [comment]
- 10220082
- Matplotlib merupakan library untuk membuat visualisasi
- https://medium.com/@desulight99/matplotlib-merupakan-library-untuk-membuat-visualisasi-6df07ef64817

**Comment by AngeliFransiskaNjo** [comment]
- 10220022
- Melakukan Plotting dengan Matplotlib
- https://medium.com/@angelifransiskanjoo/melakukan-plotting-dengan-matplotlib-ae735c509c9c

**Comment by purwariadi** [comment]
- 10219109
- Gimana cara plot pakai matplotlib?
- https://medium.com/@purwasatria/gimana-cara-plot-pakai-matplotlib-224592c7bf50

**Comment by dianatan** [comment]
- 10220038
- Cara Membuat Grafik dengan Matplotlib pada Python
- https://medium.com/@dtanoto88/cara-membuat-grafik-dengan-matplotlib-pada-python-92f53e94458d

**Comment by rafifprastya** [comment]
+ 10220033
+ https://medium.com/@rafifprastya/tentang-matplotlib-menggali-dunia-visualisasi-data-839251acd1d3
+ Tentang Matplotlib: Menggali Dunia Visualisasi Data

**Comment by ArkanantaR** [comment]
- 10220014
- Chapter 2: Skill Issues in Basic Physics Laboratory
- https://arkanantaltmpt.medium.com/chapter-2-skill-issues-in-basic-physics-laboratory-22613cac2838

**Comment by DedeAditiaa** [comment]
- 10220007
- Plot Plot Plot dengan Matplotlib
- https://medium.com/@dedeaditiaa/mari-memplotting-menggunakan-matplotlib-8d61d9172a8c

**Comment by keziaalodiac** [comment]
- 10220009
- Plotting Data with Matplotlib
- https://medium.com/@keziaalodiac/plotting-data-with-matplotlib-f94bc164e74c

**Comment by arionlubis** [comment]
- 10220047
- Tahap 2 : Matplotlib? Pyplot? Plotting?
- https://medium.com/@arionlubis/tahap-2-matplotlib-pyplot-plotting-f22e1bcb8d73

**Comment by cyukis** [comment]
+ 10220056
+ Matplotlib Sebagai Library Dasar untuk Plotting di Python
+ https://medium.com/@cyukis/matplotlib-sebagai-library-dasar-untuk-plotting-di-python-c981dcefb10f

**Comment by deyselezra** [comment]
- 10220071
- Plotting dengan Matplotlib
- https://medium.com/@deysel040402/plotting-dengan-matplotlib-31baeab24ce1

**Comment by azkabudiman21** [comment]
- 10219056
- Plotting With Matplotlib
- https://medium.com/@azkabudiman/plotting-with-matplotlib-c07074d7089a

**Comment by andrewanggoh** [comment]
+ 10220012
+ Sekilas tentang Matplotlib
+ https://medium.com/@andrew.anggoh/sekilas-tentang-matplotlib-4a0ad3d94239

**Comment by BracchialisG** [comment]
- 10220067
- Plotting dengan Matplotlib
- https://rekryanta.medium.com/plotting-dengan-matplotlib-c2671e853212
